### ISSUE TITLE
Support for `yield Sleep(x)`

### ISSUE THREAD

**Issue by bsamuel-ui** [devova/pytest-yield#5]
I have some tests that need to post a request and then poll for a result.

My present solution is a simple object:

```
def sleep(seconds, granularity=10):
    done_at = time.time() + seconds

    while True:
        sleep_to = min(time.time() + granularity, done_at)
        yield
        now = time.time()
        if now >= done_at:
            return
        if now < sleep_to:
            time.sleep(sleep_to - now)
```

And `yield from sleep(30)` will sleep for at least 30 seconds.

But I think a nicer mechanism would be to `yield pytest_yield.mark.Sleep(20)` back to the runner which could track sleeping tests in a heap and sleep until the next wakeup when only sleeping tests.

**Comment by devova** [comment]
Your solution will wait for given time for every single test.
There is an introduced by plugin pytest hook that executes every time all tests yields at least once:
```python
def pytest_round_finished():
    time.sleep(30)
```
https://github.com/devova/pytest-yield/blob/master/examples/conftest.py#L62

I have similar use case that you described and it helps me a lot.

**Comment by bsamuel-ui** [comment]
That's a bit of action at a distance, but could easily be documented and seems dramatically simpler.
